services:
  hotslab_prod:
    image: hotslab_prod
    container_name: hotslab_prod
    build:
      context: ./
      dockerfile: docker/hotslab-prod.dockerfile
    volumes:
      - ./docker/cache/prod/supervisor:/app/supervisord
      - ./docker/cache/prod/.next:/app/.next
      - prod_node_modules:/app/node_modules
      - prod_npm:/app/.npm
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=1
    extra_hosts:
    - host.docker.internal:host-gateway

volumes:
  prod_node_modules:
  prod_npm: