services:
  hotslab_prod:
    image: hotslab_prod
    container_name: hotslab_prod
    build:
      context: ./
      dockerfile: docker/hotslab-prod.dockerfile
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=1
    extra_hosts:
    - host.docker.internal:host-gateway
